# Generated by Django 2.1.5 on 2019-12-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyricwritters',
            fields=[
                ('lyricwritter_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('lyricwritter_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'lyricwritters',
                'managed': False,
            },
        ),
    ]
