# Generated by Django 2.1.5 on 2019-12-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_lyricwritters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lyricists',
            fields=[
                ('lyricist_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('lyricist_name', models.CharField(max_length=20)),
                ('lyricist_nationality', models.CharField(blank=True, max_length=20, null=True)),
                ('lyricist_birthplace', models.CharField(blank=True, max_length=20, null=True)),
                ('lyricist_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lyricists',
                'managed': False,
            },
        ),
    ]
